"""Exact I1 install once; stop on data/identity differences. No app launch."""
from pathlib import Path
import ast,importlib.util,json,hashlib,subprocess,datetime,plistlib,os
r=Path('/Users/doubleshy0n/.codex/worktrees/paired-rollout-preflight/Universe Keyboard');b=Path('/private/tmp/ukey-wake-ui-i1-20261003');i0=Path('/private/tmp/ukey-wake-ui-i0-20261003');pp=r/'docs/plans/keyboard-wake-diagnostic-extension-paired-rollout-001-c7-ui-i1-install-packet-2026-10-03.json';p=json.loads(pp.read_text());sha=lambda path:hashlib.sha256(Path(path).read_bytes()).hexdigest();assert sha(pp)==json.loads((b/'packet-identity.json').read_text())['whole_file_sha256'];before=json.loads((i0/'before-inventories.json').read_text());backup=json.loads((i0/'backup-inventories.json').read_text())
# Reuse only inspected imports/function definitions; skip all I0 backup top-level actions.
tree=ast.parse((i0/'backup-current.py').read_text());safe=ast.Module(body=[n for n in tree.body if isinstance(n,(ast.Import,ast.ImportFrom,ast.FunctionDef))],type_ignores=[]);ctx={'h':lambda data:hashlib.sha256(data).hexdigest(),'udid':'405D994F-28CB-4F89-BB22-B64AD81C05A2','bid':'com.DoubleShy0N.Universe-Keyboard','gid':'group.com.DoubleShy0N.Universe-Keyboard'};exec(compile(safe,'frozen-i0-read-functions','exec'),ctx);run=ctx['run'];inventory=ctx['inventory'];discover=ctx['discover']
spec=importlib.util.spec_from_file_location('readonly_compare',r/'docs/evidence/keyboard-wake-diagnostic-extension-paired-rollout-001-c7-ui-t-reader-preflight-artifacts/reader.py');reader=importlib.util.module_from_spec(spec);spec.loader.exec_module(reader)
def roots(paths):
 groups=dict(line.split('\t',1) for line in paths['groups'].splitlines());assert set(groups)=={ctx['gid']};return {'main-data':Path(paths['data']),'app-group':Path(groups[ctx['gid']]),'installed-app':Path(paths['app'])}
def absent():
 prefix=f'/CoreSimulator/Devices/{ctx["udid"]}/';matches=[line for line in run(['ps','-axo','pid=,comm=']).splitlines() if prefix in line and '/Universe Keyboard.app/' in line];assert not matches,'target process returned; stop'
def sigs(app):
 out={}
 for name,path in [('main',app),('keyboard',app/'PlugIns/Keyboard.appex')]:
  q=subprocess.run(['codesign','--verify','--deep','--strict',str(path)],capture_output=True,text=True);out[name]={'exit':q.returncode};assert q.returncode==0,q.stderr
 return out
assert run(['git','-C',str(r),'branch','--show-current'])==p['baseline']['branch'];assert run(['git','-C',str(r),'rev-parse','HEAD'])==p['baseline']['HEAD'];assert sha(r/'docs/evidence/keyboard-wake-diagnostic-extension-paired-rollout-001-c7-ui-i0-artifacts/backup-receipt.json')==p['fresh_backup_receipt_sha256'];assert sha(r/'docs/plans/keyboard-wake-diagnostic-extension-paired-rollout-001-c7-ui-i0-recovery-plan-2026-10-03.md')==p['recovery_plan_sha256']
inputs=json.loads((r/'docs/reviews/c7-ui-t-split-s-r2-packet-2026-10-03.json').read_text())['hash_only_source_vendor_inputs'];assert not [path for path,value in inputs.items() if sha(path)!=value]
pairedpath=r/'docs/evidence/keyboard-wake-diagnostic-extension-paired-rollout-001-c7-ui-h1-artifacts/paired-products.json';assert sha(pairedpath)==p['paired_products_sha256'];paired=json.loads(pairedpath.read_text());candidate=Path(p['candidate_path']);assert all(sha(candidate/path)==value for path,value in paired['file_hashes'].items());candidate_sigs=sigs(candidate)
oldpaths=discover();assert oldpaths==json.loads((i0/'container-discovery.json').read_text());absent();live={name:inventory(path) for name,path in roots(oldpaths).items()};assert live==before,'live origin drift since fresh backup; stop';copy_now={name:inventory(Path(p['backup_root'])/name) for name in before};assert copy_now==backup,'backup drift; stop';absent();assert discover()==oldpaths
preflight={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'all_required_checks_passed':True,'current_origins_equal_I0':True,'backup_unchanged':True,'processes_absent':True,'source_payload_hash_only_count':len(inputs),'source_payload_hash_only_mismatches':[],'candidate_signatures':candidate_sigs,'exclusive_authority':'Human explicit 授权 to I1+exclusive question','tool_fallback':'MCP defaults are another task; frozen explicit UDID argv, no defaults changed'};(b/'preflight.json').write_text(json.dumps(preflight,ensure_ascii=False,indent=2)+'\n')
assert not (b/'install-started.json').exists(),'install already attempted; no repeats';(b/'install-started.json').write_text(json.dumps({'argv':p['install_argv'],'utc':datetime.datetime.now(datetime.timezone.utc).isoformat()},indent=2)+'\n');result=subprocess.run(p['install_argv'],capture_output=True,text=True);(b/'install-receipt.json').write_text(json.dumps({'argv':p['install_argv'],'exit':result.returncode,'stdout':result.stdout,'stderr':result.stderr,'attempts':1},indent=2)+'\n');assert result.returncode==0,'install failed; no repeat'
paths=discover();(b/'postinstall-containers.json').write_text(json.dumps(paths,indent=2)+'\n');after={name:inventory(path) for name,path in roots(paths).items()};(b/'postinstall-inventories.json').write_text(json.dumps(after,ensure_ascii=False,indent=2)+'\n');absent()
# Preserve complete accessible installed after-state before deciding whether data changed.
preserved=b/'after-preservation';preserved.mkdir(mode=0o700,exist_ok=False)
for name,path in roots(paths).items():run(['/usr/bin/ditto','--rsrc','--extattr','--acl',str(path),str(preserved/name)])
copy_after={name:inventory(preserved/name) for name in after};final={name:inventory(path) for name,path in roots(paths).items()};(b/'after-backup-inventories.json').write_text(json.dumps(copy_after,ensure_ascii=False,indent=2)+'\n');(b/'final-live-inventories.json').write_text(json.dumps(final,ensure_ascii=False,indent=2)+'\n');assert after==final and discover()==paths;absent();copy_checks={name:reader.compare(after[name],copy_after[name]) for name in after};assert all(not check['missing'] and not check['added'] and not check['changed'] for check in copy_checks.values()),'after copy mismatch'
actual={path:row['sha256'] for path,row in after['installed-app'].items() if row['kind']=='file'};assert actual==paired['file_hashes'],'installed payload mismatch';installed_sigs=sigs(roots(paths)['installed-app']);uuidrows=[]
for row in paired['machos']:
 output=run(['xcrun','dwarfdump','--uuid',str(roots(paths)['installed-app']/row['path'])]);assert row['uuid'] in output;uuidrows.append({'path':row['path'],'sha256':actual[row['path']],'uuid':row['uuid']})
infos=[]
for row in paired['bundles']:
 relative=Path(row['path']).relative_to(candidate);info=plistlib.loads((roots(paths)['installed-app']/relative/'Info.plist').read_bytes());assert info['CFBundleIdentifier']==row['bundle_id'] and info['CFBundleVersion']==row['build'] and info['CFBundleShortVersionString']==row['version'];infos.append({'relative_bundle':str(relative),'bundle_id':row['bundle_id'],'build':row['build'],'version':row['version']})
diffs={name:reader.compare(before[name],after[name],True) for name in ['main-data','app-group']};snapshots_same=reader.snapshots(before['main-data'])==reader.snapshots(after['main-data']);pref=roots(paths)['app-group']/f'Library/Preferences/{ctx["gid"]}.plist';data=plistlib.loads(pref.read_bytes()) if pref.exists() else {};keys=['logging_enabled','diagnostics_high_fidelity_expiration','rime_deployed','rime_needs_deploy','rime_is_deploying'];selected={key:{'exists':key in data,'value':data.get(key)} for key in keys};expected=json.loads((i0/'backup-receipt.json').read_text())['selected_preferences'];assert selected==expected,'protected preference mismatch'
receipt={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'candidate':p['candidate'],'installed_files':len(actual),'payload_matches_H1':True,'paired_bundle_identity':infos,'six_macho_identities':uuidrows,'strict_signatures':installed_sigs,'origin_paths_changed':{name:oldpaths[name]!=paths[name] for name in ['app','data','groups']},'protected_application_differences':diffs,'snapshot_sha_multiset_same':snapshots_same,'selected_preferences':selected,'after_preserved_root':str(preserved),'after_source_two_reads_equal':True,'after_copy_bytes_structure_modes_owner_original_attrs_verified':True,'after_copy_provenance_classification':{name:x['normalized_new_attrs'] for name,x in copy_checks.items()},'processes_absent':True,'no_launch_input_probe_maps_lldb_restore':True};(b/'postinstall-verification.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps(receipt,ensure_ascii=False));assert snapshots_same and all(not x['missing'] and not x['added'] and not x['changed'] for x in diffs.values()),'protected data changed; stop and preserve, no restore'
