#!/usr/bin/env python3
"""Generate compile-time T9 syllable catalog from luna_pinyin.dict.yaml.

Usage (repo root; path is lowercase `scripts/`):
  python3 scripts/generate_t9_pinyin_syllable_catalog.py

Outputs:
  Packages/KeyboardCore/Sources/KeyboardCore/T9PinyinSyllableCatalog.generated.swift

Syllable policy (ADR 0023 / Codex Q-004-02):
  - Extract lowercase ASCII tokens from the dictionary code column.
  - Drop RIME unknown-reading placeholders (e.g. `xx`).
  - Keep only tokens that contain at least one Mandarin vowel letter a/e/i/o/u/v.
  - Baseline count is pinned; intentional source changes require ADR/test updates.
"""

from __future__ import annotations

import hashlib
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPO_ROOT / "Keyboard" / "Resources" / "luna_pinyin.dict.yaml"
OUTPUT = (
    REPO_ROOT
    / "Packages"
    / "KeyboardCore"
    / "Sources"
    / "KeyboardCore"
    / "T9PinyinSyllableCatalog.generated.swift"
)
GENERATOR_VERSION = "2"
# 418 raw unique ASCII tokens minus filtered non-pinyin placeholders (`xx`).
EXPECTED_SYLLABLE_COUNT = 417

# Explicit RIME / dictionary placeholders that are not pronounceable syllables.
PLACEHOLDER_TOKENS = frozenset({"xx", "xxx", "xxxx"})
VOWELS = frozenset("aeiouv")


def is_legal_pinyin_syllable(token: str) -> bool:
    if not token or not re.fullmatch(r"[a-z]+", token):
        return False
    if token in PLACEHOLDER_TOKENS:
        return False
    # Every legal Mandarin syllable spelling in this dictionary uses a vowel letter
    # (including ü written as v in some schemes; luna uses plain aeiou for finals).
    if not any(ch in VOWELS for ch in token):
        return False
    return True


def extract_syllables(text: str) -> list[str]:
    parts = text.split("...\n", 1)
    body = parts[1] if len(parts) > 1 else text
    syllables: set[str] = set()
    rejected: set[str] = set()
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = re.split(r"\s+", line)
        if len(fields) < 2:
            continue
        code = fields[1]
        for token in re.split(r"[^a-zA-Z]+", code):
            if not token or not re.fullmatch(r"[a-zA-Z]+", token):
                continue
            lower = token.lower()
            if is_legal_pinyin_syllable(lower):
                syllables.add(lower)
            else:
                rejected.add(lower)
    if rejected:
        print(f"filtered non-syllable tokens: {sorted(rejected)}", file=sys.stderr)
    return sorted(syllables)


def digit_signature(syllable: str) -> str:
    table = str.maketrans("abcdefghijklmnopqrstuvwxyz", "22233344455566677778889999")
    return syllable.translate(table)


def wrap_string_array(items: list[str], indent: int = 8) -> str:
    lines: list[str] = []
    cur = " " * indent
    for index, item in enumerate(items):
        piece = f'"{item}"'
        if index < len(items) - 1:
            piece += ", "
        if len(cur) + len(piece) > 100 and cur.strip():
            lines.append(cur.rstrip())
            cur = " " * indent + piece
        else:
            cur += piece
    if cur.strip():
        lines.append(cur.rstrip())
    return "\n".join(lines)


def main() -> int:
    if not SOURCE.is_file():
        print(f"error: missing source {SOURCE}", file=sys.stderr)
        return 1

    raw = SOURCE.read_bytes()
    text = raw.decode("utf-8")
    sha = hashlib.sha256(raw).hexdigest()
    version_match = re.search(r'version:\s*"([^"]+)"', text)
    source_version = version_match.group(1) if version_match else "unknown"
    ordered = extract_syllables(text)
    if len(ordered) != EXPECTED_SYLLABLE_COUNT:
        print(
            f"error: syllable count {len(ordered)} != expected {EXPECTED_SYLLABLE_COUNT}. "
            "Update ADR/tests only after intentional source change review.",
            file=sys.stderr,
        )
        return 2

    by_sig: dict[str, list[str]] = defaultdict(list)
    for syllable in ordered:
        by_sig[digit_signature(syllable)].append(syllable)

    lines = [
        "// Auto-generated by scripts/generate_t9_pinyin_syllable_catalog.py",
        "// DO NOT EDIT BY HAND. Regenerate when luna_pinyin.dict.yaml changes.",
        "import Foundation",
        "",
        "/// Compile-time T9 syllable catalog extracted from luna_pinyin.dict.yaml (ADR 0023).",
        "public enum T9PinyinSyllableCatalog {",
        f'    public static let generatorVersion = "{GENERATOR_VERSION}"',
        '    public static let sourceRelativePath = "Keyboard/Resources/luna_pinyin.dict.yaml"',
        f'    public static let sourceVersion = "{source_version}"',
        f'    public static let sourceSHA256 = "{sha}"',
        f"    public static let syllableCount = {len(ordered)}",
        '    public static let sourceLicenseNote = "Derived from in-repo luna_pinyin.dict.yaml; upstream rime-luna-pinyin is LGPL-3.0. See docs/architecture/t9-pinyin-syllable-catalog.md."',
        "",
        "    /// Unique lowercase legal syllables in stable catalog order.",
        "    public static let syllables: [String] = [",
        wrap_string_array(ordered, 8),
        "    ]",
        "",
        "    /// Digit signature → catalog-ordered complete syllables.",
        "    public static let syllablesByDigitSignature: [String: [String]] = [",
    ]
    for sig, sylls in sorted(by_sig.items(), key=lambda item: (len(item[0]), item[0])):
        arr = ", ".join(f'"{s}"' for s in sylls)
        lines.append(f'        "{sig}": [{arr}],')
    lines.extend(
        [
            "    ]",
            "",
            "    /// Catalog order ranks for O(1) Path ranking (built once).",
            "    public static let catalogRankBySyllable: [String: Int] = {",
            "        var ranks: [String: Int] = [:]",
            "        ranks.reserveCapacity(syllables.count)",
            "        for (index, syllable) in syllables.enumerated() {",
            "            ranks[syllable] = index",
            "        }",
            "        return ranks",
            "    }()",
            "",
            "    public static func completeSyllables(matchingDigits digits: String) -> [String] {",
            "        syllablesByDigitSignature[digits] ?? []",
            "    }",
            "}",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({OUTPUT.stat().st_size} bytes)")
    print(f"syllables={len(ordered)} signatures={len(by_sig)} sha256={sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
